## Recommendations
<ul>
<li>Beyond Face Rotation: Global and Local Perception GAN for Photorealistic and Identity Preserving Frontal View Synthesis <a href="https://arxiv.org/abs/1704.04086">[arXiv]</a> 
<img src="http://it-caesar.com/github/beyond-face-rotation.png" alt="Beyond face rotation"></li>

<li>Pose Guided Person Image Generation <a href="https://arxiv.org/abs/1705.09368">[arXiv]</a> 
<img src="http://it-caesar.com/github/pose-guided-person.png" alt="Pose guided person"></li>

<li>Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks <a href="https://arxiv.org/abs/1703.10593">[arXiv]</a>  
<img src="http://it-caesar.com/github/cycle-gan.png" alt="Cycle GAN"></li>
</ul>

# Tutorials & Workshops & Blogs
- Columbia Advanced Machine Learning Seminar
  - New Progress on GAN Theory and Practice [[Blog]](https://casmls.github.io/general/2017/04/13/gan.html)
  - Implicit Generative Models — What are you GAN-na do? [[Blog]](https://casmls.github.io/general/2017/05/24/ligm.html)
- How to Train a GAN? Tips and tricks to make GANs work [[Blog]](https://github.com/soumith/ganhacks)
- On the intuition behind deep learning & GANs — towards a fundamental understanding [[Blog]](https://blog.waya.ai/introduction-to-gans-a-boxing-match-b-w-neural-nets-b4e5319cc935)
- OpenAI - Generative Models [[Blog]](https://openai.com/blog/generative-models/)
- SimGANs - a game changer in unsupervised learning, self driving cars, and more [[Blog]](https://blog.waya.ai/simgans-applied-to-autonomous-driving-5a8c6676e36b)

# Code
- Cleverhans: A library for benchmarking vulnerability to adversarial examples [[Code]](https://github.com/openai/cleverhans) [[Blog]](http://cleverhans.io/)
- Generative Adversarial Networks (GANs) in 50 lines of code (PyTorch) [[Blog]](https://medium.com/@devnag/generative-adversarial-networks-gans-in-50-lines-of-code-pytorch-e81b79659e3f) [[Code]](https://github.com/devnag/pytorch-generative-adversarial-networks)
- Generative Models: Collection of generative models, e.g. GAN, VAE in Pytorch and Tensorflow [[Code]](https://github.com/wiseodd/generative-models)
- Reproduction of the GANs paper (MNIST) in 100 lines of PyTorch code  [[Blog]](https://papers-100-lines.medium.com/generative-adversarial-networks-in-100-lines-of-code-516f09d1790a) [[Code]](https://github.com/MaximeVandegar/Papers-in-100-Lines-of-Code/tree/main/Generative_Adversarial_Networks)
- Ada-StyleGAN2 [Code](https://github.com/NVlabs/stylegan2-ada)
-StyleGan3 [Code](https://github.com/NVlabs/stylegan3)


# Papers
## Overview
- Generative Adversarial Networks: An Overview [[arXiv]](https://arxiv.org/abs/1710.07035)

## Theory & Machine Learning
- A Connection between Generative Adversarial Networks, Inverse Reinforcement Learning, and Energy-Based Models [[arXiv]](https://arxiv.org/abs/1611.03852)
- Activation Maximization Generative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1703.02000)
- AdaGAN: Boosting Generative Models [[arXiv]](https://arxiv.org/abs/1701.02386)
- Adversarial Autoencoders [[arXiv]](https://arxiv.org/abs/1511.05644)
- Adversarial Discriminative Domain Adaptation [[arXiv]](https://arxiv.org/abs/1702.05464)
- Adversarial Generator-Encoder Networks [[arXiv]](https://arxiv.org/pdf/1704.02304.pdf)
- Adversarial Feature Learning [[arXiv]](https://arxiv.org/abs/1605.09782) [[Code]](https://github.com/wiseodd/generative-models)
- Adversarially Learned Inference [[arXiv]](https://arxiv.org/abs/1606.00704) [[Code]](https://github.com/wiseodd/generative-models)
- AE-GAN: adversarial eliminating with GAN [[arXiv]](https://arxiv.org/abs/1707.05474)
- An Adversarial Regularisation for Semi-Supervised Training of Structured Output Neural Networks [[arXiv]](https://arxiv.org/abs/1702.02382)
- APE-GAN: Adversarial Perturbation Elimination with GAN [[arXiv]](https://arxiv.org/abs/1707.05474)
- Associative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1611.06953)
- Autoencoding beyond pixels using a learned similarity metric [[arXiv]](https://arxiv.org/abs/1512.09300)
- Bayesian Conditional Generative Adverserial Networks [[arXiv]](https://arxiv.org/abs/1706.05477)
- Bayesian GAN [[arXiv]](https://arxiv.org/abs/1705.09558)
- BEGAN: Boundary Equilibrium Generative Adversarial Networks [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_4.pdf) [[arXiv]](https://arxiv.org/abs/1703.10717) [[Code]](https://github.com/wiseodd/generative-models)
- Binary Generative Adversarial Networks for Image Retrieval [[arXiv]](https://arxiv.org/abs/1708.04150)
- Boundary-Seeking Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1702.08431) [[Code]](https://github.com/wiseodd/generative-models)
- CausalGAN: Learning Causal Implicit Generative Models with Adversarial Training [[arXiv]](https://arxiv.org/abs/1709.02023)
- Class-Splitting Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1709.07359)
- Comparison of Maximum Likelihood and GAN-based training of Real NVPs [[arXiv]](https://arxiv.org/abs/1705.05263)
- Conditional CycleGAN for Attribute Guided Face Image Generation [[arXiv]](https://arxiv.org/abs/1705.09966)
- Conditional Generative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1411.1784) [[Code]](https://github.com/wiseodd/generative-models)
- Connecting Generative Adversarial Networks and Actor-Critic Methods [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_1.pdf)
- Continual Learning in Generative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1705.08395)
- C-RNN-GAN: Continuous recurrent neural networks with adversarial training [[arXiv]](https://arxiv.org/abs/1611.09904)
- CM-GANs: Cross-modal Generative Adversarial Networks for Common Representation Learning [[arXiv]](https://arxiv.org/abs/1710.05106)
- Cooperative Training of Descriptor and Generator Networks [[arXiv]](https://arxiv.org/abs/1609.09408)
- Coupled Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1606.07536) [[Code]](https://github.com/wiseodd/generative-models)
- Dualing GANs [[arXiv]](https://arxiv.org/abs/1706.06216)
- Deep and Hierarchical Implicit Models [[arXiv]](https://arxiv.org/abs/1702.08896)
- Energy-based Generative Adversarial Network [[arXiv]](https://arxiv.org/abs/1609.03126) [[Code]](https://github.com/wiseodd/generative-models)
- Explaining and Harnessing Adversarial Examples [[arXiv]](https://arxiv.org/abs/1412.6572)
- Flow-GAN: Bridging implicit and prescribed learning in generative models [[arXiv]](https://arxiv.org/abs/1705.08868)
- f-GAN: Training Generative Neural Samplers using Variational Divergence Minimization [[arXiv]](https://arxiv.org/abs/1606.00709) [[Code]](https://github.com/wiseodd/generative-models)
- Gang of GANs: Generative Adversarial Networks with Maximum Margin Ranking [[arXiv]](https://arxiv.org/abs/1704.04865)
- Generalization and Equilibrium in Generative Adversarial Nets (GANs) [[arXiv]](https://arxiv.org/abs/1703.00573)
- Generating images with recurrent adversarial networks [[arXiv]](https://arxiv.org/abs/1602.05110)
- Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1406.2661) [[Code]](https://github.com/goodfeli/adversarial) [[Code]](https://github.com/wiseodd/generative-models)
- Generative Adversarial Networks as Variational Training of Energy Based Models [[arXiv]](https://arxiv.org/abs/1611.01799)
- Generative Adversarial Networks with Inverse Transformation Unit [[arXiv]](https://arxiv.org/abs/1709.09354)
- Generative Adversarial Parallelization [[arXiv]](https://arxiv.org/abs/1612.04021) [[Code]](https://github.com/wiseodd/generative-models)
- Generative Adversarial Residual Pairwise Networks for One Shot Learning [[arXiv]](https://arxiv.org/abs/1703.08033)
- Generative Adversarial Structured Networks [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_14.pdf)
- Generative Cooperative Net for Image Generation and Data Augmentation [[arXiv]](https://arxiv.org/abs/1705.02887)
- Generative Moment Matching Networks [[arXiv]](https://arxiv.org/abs/1502.02761) [[Code]](https://github.com/yujiali/gmmn)
- Generative Semantic Manipulation with Contrasting GAN [[arXiv]](https://arxiv.org/abs/1708.00315)
- Image Quality Assessment Techniques Show Improved Training and Evaluation of Autoencoder Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1708.02237)
- Improved Techniques for Training GANs [[arXiv]](https://arxiv.org/abs/1606.03498) [[Code]](https://github.com/openai/improved-gan)
- Improved Training of Wasserstein GANs [[arXiv]](https://arxiv.org/abs/1704.00028) [[Code]](https://github.com/wiseodd/generative-models)
- InfoGAN: Interpretable Representation Learning by Information Maximizing Generative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1606.03657) [[Code]](https://github.com/wiseodd/generative-models)
- Inverting The Generator Of A Generative Adversarial Network [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_9.pdf)
- It Takes (Only) Two: Adversarial Generator-Encoder Networks [[arXiv]](https://arxiv.org/abs/1704.02304)
- KGAN: How to Break The Minimax Game in GAN [[arXiv]](https://arxiv.org/abs/1711.01744)
- Learning in Implicit Generative Models [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_10.pdf)
- Learning Loss for Knowledge Distillation with Conditional Adversarial Networks [[arXiv]](https://arxiv.org/abs/1709.00513)
- Learning to Discover Cross-Domain Relations with Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1703.05192) [[Code]](https://github.com/wiseodd/generative-models)
- Learning Texture Manifolds with the Periodic Spatial GAN [[arXiv]](https://arxiv.org/abs/1705.06566)
- Least Squares Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1611.04076) [[Code]](https://github.com/wiseodd/generative-models)
- Linking Generative Adversarial Learning and Binary Classification [[arXiv]](https://arxiv.org/abs/1709.01509)
- Loss-Sensitive Generative Adversarial Networks on Lipschitz Densities [[arXiv]](https://arxiv.org/abs/1701.06264)
- LR-GAN: Layered Recursive Generative Adversarial Networks for Image Generation [[arXiv]](https://arxiv.org/abs/1703.01560)
- MAGAN: Margin Adaptation for Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1704.03817) [[Code]](https://github.com/wiseodd/generative-models)
- Maximum-Likelihood Augmented Discrete Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1702.07983)
- McGan: Mean and Covariance Feature Matching GAN [[arXiv]](https://arxiv.org/abs/1702.08398)
- Message Passing Multi-Agent GANs [[arXiv]](https://arxiv.org/abs/1612.01294)
- MMD GAN: Towards Deeper Understanding of Moment Matching Network [[arXiv]](https://arxiv.org/abs/1705.08584)
- Mode Regularized Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1612.02136) [[Code]](https://github.com/wiseodd/generative-models)
- Multi-Agent Diverse Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1704.02906)
- Multi-Generator Gernerative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1708.02556)
- Objective-Reinforced Generative Adversarial Networks (ORGAN) for Sequence Generation Models [[arXiv]](https://arxiv.org/abs/1705.10843)
- On Convergence and Stability of GANs [[arXiv]](https://arxiv.org/abs/1705.07215)
- On the effect of Batch Normalization and Weight Normalization in Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1704.03971)
- On the Quantitative Analysis of Decoder-Based Generative Models [[arXiv]](https://arxiv.org/abs/1611.04273)
- Optimizing the Latent Space of Generative Networks [[arXiv]](https://arxiv.org/abs/1707.05776)
- Parametrizing filters of a CNN with a GAN [[arXiv]](https://arxiv.org/abs/1710.11386)
- PixelGAN Autoencoders [[arXiv]](https://arxiv.org/abs/1706.00531)
- Progressive Growing of GANs for Improved Quality, Stability, and Variation [[arXiv]](https://arxiv.org/abs/1710.10196) [[Code]](https://github.com/tkarras/progressive_growing_of_gans)
- Simple Black-Box Adversarial Perturbations for Deep Networks [[Paper]](https://c4209155-a-62cb3a1a-s-sites.googlegroups.com/site/nips2016adversarial/WAT16_paper_11.pdf)
- Softmax GAN [[arXiv]](https://arxiv.org/abs/1704.06191)
- Stabilizing Training of Generative Adversarial Networks through Regularization [[arXiv]](https://arxiv.org/abs/1705.09367)
- Stacked Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1612.04357)
- Statistics of Deep Generated Images [[arXiv]](https://arxiv.org/abs/1708.02688)
- Structured Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1711.00889)
- Tensorizing Generative Adversarial Nets [[arXiv]](https://arxiv.org/abs/1710.10772)
- The Cramer Distance as a Solution to Biased Wasserstein Gradients [[arXiv]](https://arxiv.org/abs/1705.10743)
- Towards Understanding Adversarial Learning for Joint Distribution Matching [[arXiv]](https://arxiv.org/abs/1709.01215)
- Training generative neural networks via Maximum Mean Discrepancy optimization [[arXiv]](https://arxiv.org/abs/1505.03906)
- Unrolled Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1611.02163)
- Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks [[arXiv]](https://arxiv.org/abs/1511.06434) [[Code]](https://github.com/Newmu/dcgan_code) [[Code]](https://github.com/pytorch/examples/tree/master/dcgan) [[Code]](https://github.com/carpedm20/DCGAN-tensorflow) [[Code]](https://github.com/soumith/dcgan.torch) [[Code]](https://github.com/jacobgil/keras-dcgan)
- Wasserstein GAN [[arXiv]](https://arxiv.org/abs/1701.07875) [[Code]](https://github.com/martinarjovsky/WassersteinGAN) [[Code]](https://github.com/wiseodd/generative-models)
